services:
  caddy:
    image: caddy:2-alpine
    container_name: app_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Used by Caddy for ACME registration
      - ACME_EMAIL=${ACME_EMAIL}
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
      - PMA_BCRYPT_HASH=${PMA_BCRYPT_HASH}
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./docker/caddy/Caddyfile.local:/etc/caddy/Caddyfile.local:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nginx
      - phpmyadmin
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  phpmyadmin:
    image: phpmyadmin:5-apache
    container_name: app_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - UPLOAD_LIMIT=100M
      - PMA_ABSOLUTE_URI=https://${APP_DOMAIN:-localhost}/pma/
    depends_on:
      - mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:1.27-alpine
    container_name: app_nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/sites:/etc/nginx/conf.d:ro
      - ./src:/var/www/html:delegated
    depends_on:
      - php
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  php:
    build:
      context: ./docker/php
    container_name: app_php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:delegated
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  mysql:
    image: mysql:8.4
    container_name: app_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  caddy_data:
  caddy_config:
  mysql_data:

networks:
  appnet:
    driver: bridge